import {
  app,
  Menu,
  nativeImage,
  Tray,
  type MenuItemConstructorOptions
} from 'electron'
import type { Module, ModuleRegistry } from '../core/ModuleRegistry'
import type { WindowModule } from './WindowModule'
import type { HotkeyModule } from './HotkeyModule'
import type { UpdaterModule } from './UpdaterModule'

// 16x16 (1x) + 32x32 (2x retina) tray template — black squircle with
// Helvetica Bold "R" cut out via alpha subtract. Generated by
// scripts/generate-icon.py. macOS template image → auto-adapts to
// light/dark menu bar.
const TRAY_ICON_1X =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAmElEQVR4nGNkQAX/GYgDjOiM/0RqxDCIiUyNKE75T4kBTFjEHkANRsYSDAwMs3EZ8h8N34eK10P5vxgYGJKhlt1CV89EhCtZGRgY3BkYGP4xMDBcJsYL6OA3AwPDHqhBhqR4AR2UYFH7n5gw+MbAwOABdcFHcsKAk4GBwQDqldfokkwMxAFRKH2DJgmJkQL91MkLyIDk7AwAl9QxJCY8wLIAAAAASUVORK5CYII='
const TRAY_ICON_2X =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABHklEQVR4nO2XMU7DMBSGP79UlVgYK7F05xRdGFgqeoIuHbgGR+gOJ+jQpTswcQD2DoxMVbu2xcgoDU6UtLYU20Xik54UPTnv/23nOYmiHk0Y1KmEDiTcqCsJxEtakkC8ZEJIjEo0+wJJKf6nDLzm29UUGdADboCZrwntEC+eNR8c6+pQBjrAu0ttwZ+sptAaeMqFDTvgMeZDeAlMgIGV+4hp4EC3uIIrHOjQDhtgDjxbuVEoA/u612qFMXDrWlC33AVDYOvahkL7LIB7nxu05wpU29DMdgncWWPMxD5DHURZwxhz8Ni8xd6Cfk1nnEQCnQGGr9gGLvI4sIptwHDNL1McUP+fZJyBAZVQX53FCpBoFX40pZqIKX5MNNrv+Te+T4u60RVJuwAAAABJRU5ErkJggg=='

/**
 * TrayModule — menu bar tray icon + dynamic context menu. Menu rebuilds
 * whenever HotkeyModule.register or UpdaterModule's state changes (those
 * modules call rebuildMenu directly).
 */
export class TrayModule implements Module {
  private tray: Tray | null = null

  constructor(private reg: ModuleRegistry) {}

  bootstrap(): void {
    const icon = nativeImage.createFromBuffer(Buffer.from(TRAY_ICON_1X, 'base64'))
    icon.addRepresentation({
      scaleFactor: 2,
      buffer: Buffer.from(TRAY_ICON_2X, 'base64')
    })
    icon.setTemplateImage(true)
    this.tray = new Tray(icon)
    this.tray.setToolTip('Rift')
    this.rebuildMenu()
  }

  rebuildMenu(): void {
    if (!this.tray) return
    const window = this.reg.get<WindowModule>('window')
    const hotkey = this.reg.get<HotkeyModule>('hotkey')
    const updater = this.reg.get<UpdaterModule>('updater')

    const menu = Menu.buildFromTemplate([
      {
        label: 'Show Rift',
        accelerator: hotkey.current() || undefined,
        click: () => window.show()
      },
      { type: 'separator' },
      {
        label: 'Settings…',
        accelerator: 'Cmd+,',
        click: () => window.openSettings()
      },
      { type: 'separator' },
      this.updateMenuItem(updater),
      { type: 'separator' },
      {
        label: 'Quit Rift',
        accelerator: 'Cmd+Q',
        click: () => app.quit()
      }
    ])
    this.tray.setContextMenu(menu)
  }

  private updateMenuItem(updater: UpdaterModule): MenuItemConstructorOptions {
    const state = updater.state()
    const version = updater.version()
    switch (state) {
      case 'checking':
        return { label: 'Checking for updates…', enabled: false }
      case 'downloading':
        return {
          label: `Downloading ${version ? `v${version}` : 'update'}…`,
          enabled: false
        }
      case 'ready':
        return {
          label: `Restart to install${version ? ` v${version}` : ''}`,
          click: () => updater.installNow()
        }
      default:
        return {
          label: 'Check for updates…',
          click: () => updater.check(false)
        }
    }
  }
}
